name: Stage Build - Zabbix Server

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: zabbix
  CHAMBER_VERSION: v3.1.1
  ALPINE_VERSION: 3.21
  MAJOR_VERSION: 7.0
  ZBX_PATCH_VERSION: 11
  ZBX_VERSION: 7.0.11
  BUILD_BASE_IMAGE: "zabbix-server-pgsql:alpine-7.0.11"
  DOCKER_REGISTRY_VERSION: "server-pgsql-alpine-7.0.11"
  ECR_REGISTRY: 326721711311.dkr.ecr.eu-west-2.amazonaws.com

permissions:
  contents: read

jobs:
  ############################### Build ###############################
  staging:
    name: Staging build
    runs-on: [self-hosted, ohmpv2, staging]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}

      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-Alpine-7.0.11
          push: true
          tags: ${{ env.ECR_REGISTRY }}
          build-args: |
            - CHAMBER_VERSION=${{ env.CHAMBER_VERSION }}
            - MAJOR_VERSION=${{ env.MAJOR_VERSION }}
            - ZBX_VERSION=${{ env.ZBX_VERSION }}
            - BUILD_BASE_IMAGE=${{ env.BUILD_BASE_IMAGE }}
            - ALPINE_VERSION=${{ env.ALPINE_VERSION }}
